[package]
name = "cli-toolbox"
version = "0.1.0"
edition = "2018"
description = "Utility library for working with cli output ergonomically"
license-file = "LICENSE-MIT"
repository = "https://github.com/Nejat/cli-toolbox-rs"
keywords = ["cli", "output", "report", "verbosity", "debug"]
categories = ["Command-line interface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0"

[dev-dependencies]
gag = "1.0"